SELECT ATENDIME.CD_ATENDIMENTO
      ,PACIENTE.CD_PACIENTE
      ,PACIENTE.NM_PACIENTE
      ,trunc((months_between(sysdate,PACIENTE.dt_nascimento))/12) IDADE
      ,PACIENTE.TP_SEXO
      ,ATENDIME.DT_ATENDIMENTO
      ,ATENDIME.TP_ATENDIMENTO
      ,ATENDIME.CD_CID
      ,CID.DS_CID
      ,LEITO.CD_UNID_INT
      ,UNID_INT.DS_UNID_INT
FROM ATENDIME ATENDIME
INNER JOIN PACIENTE PACIENTE
  ON PACIENTE.CD_PACIENTE = ATENDIME.CD_PACIENTE
INNER JOIN CID CID
  ON CID.CD_CID = ATENDIME.CD_CID
INNER JOIN LEITO LEITO
  ON LEITO.CD_LEITO = ATENDIME.CD_LEITO
INNER JOIN UNID_INT UNID_INT
  ON UNID_INT.CD_UNID_INT = LEITO.CD_UNID_INT
WHERE ATENDIME.CD_CID IN ('I500','I501','I509')
AND ATENDIME.DT_ATENDIMENTO BETWEEN '01/01/2015' AND '09/09/2020'
AND trunc((months_between(sysdate,PACIENTE.dt_nascimento))/12) >= 60
AND UNID_INT.CD_UNID_INT IN ('30','32','44')
ORDER BY ATENDIME.DT_ATENDIMENTO 
        ,UNID_INT.DS_UNID_INT
;

      